# Generated by Django 3.2.13 on 2022-11-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types_of_Freight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarding', models.CharField(max_length=30)),
                ('consolidated_refrigerated_cargo', models.CharField(max_length=50)),
                ('transportation_of_medicines', models.CharField(max_length=60)),
                ('transportation_of_food', models.CharField(max_length=30)),
                ('transportation_of_building_materials', models.CharField(max_length=50)),
                ('logistics_and_routing', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-forwarding'],
            },
        ),
    ]
