# Generated by Django 3.2.13 on 2022-11-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_Of_Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('shipping_cost', models.CharField(max_length=75)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-country'],
            },
        ),
        migrations.CreateModel(
            name='Delivery_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shipping_cost', models.CharField(max_length=75)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Delivery_Method_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shipping_cost', models.CharField(max_length=75)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Our_Services_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/serviceimages')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='VolumeCargo',
            new_name='LengthCargo',
        ),
    ]
